### ISSUE TITLE
What is the benifit of the phpunit.xml file?

### ISSUE THREAD

**Issue by devmsh** [laracamp/session03#1]
Can you read and try to figure the purpose of phpunit.xml file?

**Comment by mawadameshal** [comment]
Is configuration file that add all *Test classes that are found in *Test.php files when the tests directory is recursively traversed. And can also be used to compose a test suite.

**Comment by anasanwar** [comment]
https://phpunit.de/manual/current/en/appendixes.configuration.html

من ضمن الشغلات اللي لفتت انتباهي انك ممكن تعمل 
Logging 
للتستس اللي بتنفذها

**Comment by kabusaid** [comment]
ملف أكثر من رائع يوفر ميزتين هما

الاولى : عمل تنفيذ لمجموعة من التست في مجلد معين
مثلا عندي 50 تست في كل المشروع عايز انفذ 4 تست فقط اضعهم في مجلد وانشا ملف اكس ام ال واعمله تنفيذ

الثانية : عمل تنفيذ لمجموعة من التست بترتيب معين احدده في الملف
:+1:

**Comment by RamiKerenawi** [comment]
This file contains more than one element, each has a role:
<phpunit>: includes all configurations for PHPUnit App.
<testsuites> to register tests we want to made in our project, you can add groups of tests to implement them together.
<groups> to collect all tests you want to implement at one time
<filter> to configure the whitelist for the code coverage reporting  
Code Coverage: if you have test the code block/class/component one time at least, then you covers this code in test.
<logging> you can configure to logging of test execution 
.
.
.
