### ISSUE TITLE
Other asserts method

### ISSUE THREAD

**Issue by devmsh** [laracamp/session03#2]
In our first test, we use an inherited method called `assertEquals`, is there any other method that can replace it and expect always that the return value is `true`?

**Comment by mawadameshal** [comment]
Maybe 
assertFalse() , assertTrue() , assertThat() .....

**Comment by AboSaleem** [comment]
assertTrue()  this method will return true, when a condition is true .

**Comment by mohuml** [comment]
assertSame(); retuen error message if the 2 compared variables don't have the same type and value.

**Comment by RamiKerenawi** [comment]
assert Function 
This Function can be used to return (true or false) or String, also it can be used to check database connection or SQL execution
by CALLBACK method and assert_options();
You may type your own warning message in second parameter as the first parameter is for comparing results.

**Comment by Wafaa122** [comment]
assertSame

**Comment by hdswe** [comment]
assertNotEqual($x, $y)      >>  Fail if $x == $y is true
assertIdentical($x, $y)       >>  Fail if $x == $y is false or a type mismatch
assertNotIdentical($x, $y)  >> Fail if $x == $y is true and types match
