### ISSUE TITLE
Next step?

### ISSUE THREAD

**Issue by devmsh** [laracamp/session03#3]
As you can see, the [Login](https://github.com/laracamp/session03/blob/master/src/Auth.php#L7) method is just returning true.

What is the next test we can write? try to add sample code to your answers.

**Comment by kabusaid** [comment]
testUserExistInDatabase
testPasswordIsCorrectForUser

testUserExistInDatabase
	$user = new User();
        $user->username = "Khaled Said";

	$userManager = new UserManager();
	$this->assertEquals(true,$userManager->isExist($user));

**Comment by anasanwar** [comment]
testValidationOfUsernameAndPassword
$this->assertEquals(true,$userManager->isValid($user));

**Comment by mawadameshal** [comment]
maybe the next step to verify that the user exists and have correct password
$this->assertTrue(Login("Name", "Password"));

or not to verify to  the user with wrong password
$this->assertFalse(Login("Name", "BadPassword"));

**Comment by RamiKerenawi** [comment]
Next Step:
1) Validate User Name and Password
IsUserExists
IsEnteredPasswordMatchesUserPassword
2) Hashing Password
EncryptPassword
SaveEncryptedPassword
IsPasswordSavedEncrypted
3) Check User Name and Encrypted Password
IsUserExists
Decrypt User Saved Password
IsDecryptedPasswordMatchesEnteredPassword  
.
.

**Comment by hamzahamada** [comment]
The Next Step : edit  the login function to return true if the username and the password are exist in the model or database.

```
function login(User){

if (DBConn->isExist(User)){
return true;
}
else { return false;}
```

**Comment by hdswe** [comment]
The test 
`<?php 
	use PHPUnit\Framework\TestCase;
	class UserExist extends TestCase{
		public function testIfUserExistInDatabase(){
			$user = new User();
			$user->username="Abdallah"
			
			$auth = new $Auth();
			$this->assertNotEquals(false,$auth->userExist($user))
		}
	}`

and we should add userExist() function in Auth class

`public function userExist($username)
	{
	$sql=mysql_query("SELECT FROM users (username) WHERE username=$username");
 if(mysql_num_rows($sql)>=1)
   {
    return true;
   }

	}`
